# URL base para tu sitio (GitHub Pages)

#Desarrollo
baseURL = "/"
# Ajustes de URLs
canonifyURLs = true
relativeURLs = true

# Producción
#baseURL = "https://jaem.dev/"
# Ajustes de URLs
#canonifyURLs = true
#relativeURLs = false

# Idioma, título y tema
languageCode = "es"
title = "JAEM"
theme = "hugo-jaem-theme"

# Carpeta donde se guardará el sitio generado por Hugo
publishDir = "docs"

# Ajustes de Pygments / Chroma
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Paginación
[pagination]
  pagerSize = 6

[menu]
  [[menu.main]]
    name  = "Acerca"
    url   = "/about/"
    weight = 10
  [[menu.main]]
    name  = "Servicios"
    url   = "/services/"
    weight = 20
  [[menu.main]]
    name  = "Posts"
    url   = "/posts/"
    weight = 30
  [[menu.main]]
    name  = "Proyectos"
    url   = "/projects/"
    weight = 40


# Configuración para resaltado de código (Chroma)
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNumbersInTable = false
    style = "dracula"  # Puedes cambiar a otro tema si lo deseas
    noClasses = false  # Usar clases CSS en lugar de estilos inline
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Permitir HTML raw en markdown

[params]
  # Nombre y redes
  name = "José Escobar"
  google_analytics_id = ""
  twitter_handle = "@JAEM_Developer"

  # Visualización de autor y robots
  enableRobotsTXT = true

  # Mostrar publicaciones en la página de inicio
  showPostsOnHomepage = true

  # Ordenar por fecha descendente (más nuevo primero)
  defaultContentOrder = "-date"

  # Post destacado en la página de inicio
  featuredPost = "posts/dotnet/windowsforms/"  # Ruta relativa al post destacado
  showFeaturedPost = true  # true para mostrar, false para ocultar

  # Hojas de estilo adicionales (Bootstrap y highlight.js)
  css = [
    "/css/chroma-syntax.css", # Estilos para el resaltado de sintaxis de Chroma
    "/css/NewStyles.css",
    
    "/css/variables.css",
    "/css/base.css",
    "/css/header.css",
    "/css/components.css",
    "/css/footer.css",
    "/css/utilities.css",
    "/css/responsive.css"
  ]
  js = [
    "/js/scripts.js"
  ]
