# URL base para tu sitio (GitHub Pages)
baseURL = "https://j0se-esc0bar.github.io/"

# Ajustes de URLs
canonifyURLs = true
relativeURLs = true

# Idioma, título y tema
languageCode = "es"
title = "JAEM"
theme = "hugo-jaem-theme"

# Carpeta donde se guardará el sitio generado por Hugo
publishDir = "docs"

# Ajustes de Pygments / Chroma
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Paginación
paginate = 7

# Configuración para resaltado de código (Chroma)
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNumbersInTable = false
    style = "dracula"  # Puedes cambiar a otro tema si lo deseas

[params]
  # Nombre y redes
  name = "José Escobar"
  google_analytics_id = ""
  twitter_handle = "@JAEM_Developer"

  # Visualización de autor y robots
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  enableRobotsTXT = true

  # Mostrar publicaciones en la página de inicio
  showPostsOnHomepage = true

  # Hojas de estilo adicionales (Bootstrap y highlight.js)
  css = [
    "https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.7.0/styles/github-dark.min.css",
    "/css/styles_manual.css"
  ]
