# URL base para tu sitio (GitHub Pages)

#Desarrollo
baseURL = "/"
# Ajustes de URLs
canonifyURLs = true
relativeURLs = true

# Producción
#baseURL = "https://jaem.dev/"
# Ajustes de URLs
#canonifyURLs = true
#relativeURLs = false

# Idioma, título y tema
languageCode = "es"
title = "JAEM"
theme = "hugo-jaem-theme"

# Carpeta donde se guardará el sitio generado por Hugo
publishDir = "docs"

# Configuración de Módulos de Hugo para encontrar dependencias en node_modules
# Se intentará un enfoque más simple primero, confiando en que Hugo busque en node_modules.
# Si esto no funciona, se puede volver a la configuración de montaje explícita
# después de resolver los errores de plantilla.
[module]
  # Montar el directorio 'static' como un directorio de recursos para Hugo Pipes
  [[module.mounts]]
    source = "static"
    target = "assets"
  # Montar Bootstrap desde node_modules
  [[module.mounts]]
    source = "node_modules/bootstrap/scss"
    target = "assets/scss/bootstrap"
  [[module.mounts]]
    source = "node_modules/bootstrap/dist/js"
    target = "assets/js/bootstrap/dist"

# Ajustes de Pygments / Chroma
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Paginación
[pagination]
  pagerSize = 6

[menu]
  [[menu.main]]
    name  = "Acerca"
    url   = "/about/"
    weight = 10
  [[menu.main]]
    name  = "Servicios"
    url   = "/services/"
    weight = 20
  [[menu.main]]
    name  = "Posts"
    url   = "/posts/"
    weight = 30
  [[menu.main]]
    name  = "Proyectos"
    url   = "/projects/"
    weight = 40


# Configuración para resaltado de código (Chroma)
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNumbersInTable = false
    style = "dracula"  # Puedes cambiar a otro tema si lo deseas
    noClasses = false  # Usar clases CSS en lugar de estilos inline
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Permitir HTML raw en markdown

[params]
  # Nombre y redes
  name = "José Escobar"
  google_analytics_id = ""
  twitter_handle = "@JAEM_Developer"

  # Visualización de autor y robots
  enableRobotsTXT = true

  # Mostrar publicaciones en la página de inicio
  showPostsOnHomepage = true

  # Ordenar por fecha descendente (más nuevo primero)
  defaultContentOrder = "-date"

  # Post destacado en la página de inicio
  featuredPost = "posts/dotnet/windowsforms/"  # Ruta relativa al post destacado
  showFeaturedPost = true  # true para mostrar, false para ocultar

  # Hojas de estilo adicionales
  # main.css y enhanced.css se cargan directamente en baseof.html
  # bootstrap.css se genera y enlaza mediante Hugo Pipes en baseof.html
  css = [
    "/css/chroma-syntax.css" # Mantener si se usa Chroma y se carga explícitamente
    # Los archivos CSS antiguos como NewStyles.css, variables.css, etc.,
    # y los CSS de Bootstrap CDN han sido eliminados o reemplazados.
  ]
  js = [
    "/js/scripts.js" # scripts.js se carga desde baseof.html
    # bootstrap.bundle.js se genera y enlaza mediante Hugo Pipes en baseof.html
  ]
